### ISSUE TITLE
Document algorithm or properties of Quantile

### ISSUE THREAD

**Issue by droundy** [vks/average#18]
I'm reduced to reading the code to try to determine whether Quantile will be appropriate for my use case.  And I'm not able to very easily determine any properties of the algorithm other than that it will be exact for five or fewer samples.

**Comment by droundy** [comment]
For instance, you claim unbounded error, but I imagine the value is constrained to be between the minimum and maximum sample?

And under what conditions would you expect it to either converge or fail to converge, if such conditions exist?

**Comment by vks** [comment]
It uses the algorithm referenced in the source code:
```

**Comment by vks** [comment]
The algorithm is detailed in the paper referenced in the source code:
```
// This uses the P² algorithm introduced here:
// http://www.cs.wustl.edu/~jain/papers/ftp/psqr.pdf
```
I'm not use why I decided to exclude it from the docs, maybe it should be there.

> For instance, you claim unbounded error, but I imagine the value is constrained to be between the minimum and maximum sample?

Many quantile algorithm use memory as a function of the number of samples and can therefore provide strict error bounds, i.e. that the relative error of the quantile is smaller than `eps * n` where `eps` is chosen by the user and `n` is the number of samples. (This is a trade-off, because because memory usage will necessarily increase with `1/eps` and `n`.)  The algorithm used by this crate does not provide such bounds, which is what I meant with "unbound" (i.e. "not bound by a function of the number of samples"). There is an upper error bound as you noted, but crucially only for the specific observed samples and not just their number. For many distributions the maximum or minimum of the samples don't converge, which means that this error bound does not either. (Arguably, this is therefore not really an error bound.)

I'll try to clarify the documentation.

> And under what conditions would you expect it to either converge or fail to converge, if such conditions exist?

I think the paper only provides empirical studies of convergence for specific distributions, including a non-continuous one. The authors recommend against using the algorithm for discrete distributions if only a small number of samples is available and for quantiles close to a discontinuity in the distribution. In general, I think it is prudent to test this algorithm against more traditional ones (for instance, just sorting the samples) with the distribution from your specific use case.

**Comment by vks** [comment]
@droundy What do you think of this?

```rust
/// The [P² algorithm][1] is employed. It uses constant space but the relative
/// error of the quantile estimate is not bounded by a function of the number of
/// samples. For algorithms that use growing space with bounded error, see the
/// [`quantiles`][2] crate.
///
/// It is recommended to use a different algorithm for discrete distributions
/// and a small number of samples, or for quantiles close to a singularity in
/// the distribution.
///
/// [1] http://www.cs.wustl.edu/~jain/papers/ftp/psqr.pdf
/// [2] https://crates.io/crates/quantiles
```

**Comment by droundy** [comment]
That sounds like a big improvement, particularly the link to the algorithm, which I missed when I looked at the source code.

**Comment by vks** [comment]
Ok, thanks for the feedback! I updated the docs. Please feel free to reopen if you think something else is missing.
