### ISSUE TITLE
Implement `std::iter::FromIterator<&f64>`

### ISSUE THREAD

**Issue by robsmith11** [vks/average#8]
I might be missing something obvious as I'm new to Rust, but why not implement `from_iter` for `&f64`?  Usually I'll have an iterator of references, so I must manually copy the values:
```
    let a:Vec<f64> = vec![1.0, 2.0, 12.0];
    let k:Kurtosis = a.iter().map(|x| *x).collect();
    println!("{:?}", k.kurtosis());
```
otherwise I'll get the error:
```
error[E0277]: the trait bound `average::Kurtosis: std::iter::FromIterator<&f64>` is not satisfied
  --> src/main.rs:24:31
   |
24 |     let k:Kurtosis = a.iter().collect();
   |                               ^^^^^^^ a collection of type `average::Kurtosis` cannot be built from an iterator over elements of type `&f64`
   |
   = help: the trait `std::iter::FromIterator<&f64>` is not implemented for `average::Kurtosis`
```

**Comment by vks** [comment]
Yes, this is a known papercut. I decided to do it this way, because it is not so clear how it should be done for the weighted statistics, which take `(f64, f64)` iterators. Should they support `&(f64, f64)`, `(&f64, f64)` etc.?  There might be some implications on type inference as well.

Another option is to implement `FromIterator<T>` for `T: Into<f64>`, but that is probably a bad idea.

Looking at the standard library:
```rust
impl<'a> FromIterator<&'a char> for String { ... }
impl FromIterator<char> for String { ... }
```
So I probably will implement `FromIterator<&f64>` and `FromIterator<&(f64, f64)>`.

**Comment by vks** [comment]
This breaks the following code:
```rust
let a: Min = (1..6).map(Into::into).collect();
```
However, it can be fixed by being more explicit (which is probably better anyway):
```rust
let a: Min = (1..6).map(f64::from).collect();
```
